version: '3'

networks:
   wkhtmltopdf_microservice:
      external: false

services:
   wkhtmltopdf:
      container_name: wkhtmltopdf_service
      image: umex/wkhtmltopdf-microservice:1.1-alpine
      ports:
         -  "9100:9100"
      environment:
         MAX_REQUESTS: 1
      restart: unless-stopped
      networks:
         - wkhtmltopdf_microservice
